# Generated by Django 4.2 on 2025-04-30 11:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0003_remove_customuser_name_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent'), ('lease', 'Lease')], max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('leased', 'Leased')], default='available', max_length=10)),
                ('brochure', models.FileField(blank=True, null=True, upload_to='brochures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('floor_plan', models.FileField(blank=True, null=True, upload_to='floor_plans/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
