# Generated by Django 4.2 on 2025-05-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0004_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
